"""The bot, the tunnel and the webhook, in one command.

    uv run python scripts/serve_bot.py

Notebook 09 walks you through the three pieces separately, and that is the
part worth understanding: a process, a tunnel that gives it a public address,
and a webhook registration that points Telegram at it. This script is what you
write *after* you have understood them — the thing you actually run on the
days you just want to ask your agent a question.

It does four things the manual route makes you do by hand:

    generates a webhook secret the first time, and remembers it in `.env`
    waits for the bot to be listening before telling Telegram about it
    reads the tunnel URL out of cloudflared instead of you copying it
    deletes the webhook on the way out, so nothing is left pointing at a
      tunnel that no longer exists

By default the archivist answers. `--team` puts the notebook 06 team behind
the bot instead, which routes between the documents and the sightings table
and costs about four times as many model calls per message.

Stop it with Ctrl+C.
"""

from __future__ import annotations

import argparse
import os
import re
import secrets
import signal
import socket
import subprocess
import sys
import time
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(REPO_ROOT))

from stargate.config import settings  # noqa: E402

PORT = 7777
ENV_FILE = REPO_ROOT / ".env"
SECRET_KEY = "TELEGRAM_WEBHOOK_SECRET_TOKEN"
TUNNEL_URL = re.compile(r"https://[a-z0-9-]+\.trycloudflare\.com")
API = "https://api.telegram.org/bot{token}/{method}"


def ensure_secret() -> str:
    """A webhook secret that survives restarts, generated once.

    Agno rejects every update that is not signed with this, so it is not
    optional — and it has to be the same string here and in `.env`, or the
    manual route in notebook 09 stops working the moment this script has run.
    """
    existing = settings().telegram_webhook_secret
    if existing:
        return existing

    secret = secrets.token_urlsafe(32)
    line = f"\n# Generated by scripts/serve_bot.py. Any hard-to-guess string works.\n{SECRET_KEY}={secret}\n"
    if ENV_FILE.exists():
        ENV_FILE.write_text(ENV_FILE.read_text().rstrip("\n") + "\n" + line)
        print(f"Wrote a new {SECRET_KEY} into .env")
    else:
        raise SystemExit(
            "No .env file. Copy .env.example to .env first — see PHASE0.md, *Fill in your keys*."
        )
    os.environ[SECRET_KEY] = secret
    settings.cache_clear()
    return secret


def telegram(method: str, **params: object) -> dict[str, object]:
    import httpx

    token = settings().telegram_token
    response = httpx.post(API.format(token=token, method=method), json=params, timeout=20)
    payload: dict[str, object] = response.json()
    if not payload.get("ok"):
        raise SystemExit(f"Telegram refused {method}: {payload.get('description')}")
    return payload


def wait_until_listening(port: int, timeout: float = 60.0) -> None:
    """Register the webhook only once there is something to receive it."""
    deadline = time.monotonic() + timeout
    while time.monotonic() < deadline:
        with socket.socket() as probe:
            probe.settimeout(1.0)
            if probe.connect_ex(("127.0.0.1", port)) == 0:
                return
        time.sleep(0.5)
    raise SystemExit(f"The bot did not start listening on port {port}. Check the output above.")


def read_tunnel_url(process: subprocess.Popen[str], timeout: float = 60.0) -> str:
    """cloudflared prints its URL into a box on stderr. Fish it out."""
    deadline = time.monotonic() + timeout
    assert process.stderr is not None
    while time.monotonic() < deadline:
        line = process.stderr.readline()
        if not line:
            if process.poll() is not None:
                raise SystemExit("cloudflared exited before printing a URL.")
            continue
        found = TUNNEL_URL.search(line)
        if found:
            return found.group(0)
    raise SystemExit("cloudflared did not print a tunnel URL within a minute.")


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--team",
        action="store_true",
        help="answer with the notebook 06 team instead of the archivist",
    )
    args = parser.parse_args()

    cfg = settings()
    if not cfg.telegram_token:
        raise SystemExit("TELEGRAM_TOKEN is not set — see PHASE0.md, *Get a Telegram bot token*.")

    secret = ensure_secret()
    me = telegram("getMe")["result"]
    username = me["username"]  # type: ignore[index]

    # The bot's output goes straight to this console; only cloudflared's is
    # captured, because we have to read a URL out of it.
    bot: subprocess.Popen[bytes] | None = None
    tunnel: subprocess.Popen[str] | None = None
    try:
        print(f"Starting the bot on port {PORT} ...")
        # uvicorn imports `telegram_bot` in a subprocess, so the choice of brain
        # travels in the environment rather than as an argument.
        bot = subprocess.Popen(
            [
                sys.executable,
                "-m",
                "uvicorn",
                "telegram_bot:app",
                "--host",
                "0.0.0.0",
                "--port",
                str(PORT),
            ],
            cwd=REPO_ROOT,
            env={**os.environ, "STARGATE_BRAIN": "team" if args.team else "archivist"},
        )
        wait_until_listening(PORT)

        print("Opening the tunnel ...")
        try:
            tunnel = subprocess.Popen(
                ["cloudflared", "tunnel", "--url", f"http://localhost:{PORT}"],
                stderr=subprocess.PIPE,
                stdout=subprocess.DEVNULL,
                text=True,
            )
        except FileNotFoundError:
            raise SystemExit(
                "cloudflared is not installed — it ships in the Codespace image, "
                "so rebuild the container if it is missing."
            ) from None
        public_url = read_tunnel_url(tunnel)

        telegram("setWebhook", url=f"{public_url}/telegram/webhook", secret_token=secret)
        print(f"\nWebhook registered:  {public_url}/telegram/webhook")
        print(f"Talk to your bot:    https://t.me/{username}")
        if cfg.telegram_restricted:
            allowed = ", ".join(str(i) for i in sorted(cfg.telegram_allowed_chat_ids))
            print(f"Answering only:      chat {allowed}")
        else:
            print(
                "Answering:           anyone who finds it. Send it a message, then put the "
                "chat id\n                     it prints into TELEGRAM_ALLOWED_CHAT_IDS in .env."
            )
        print("\nCtrl+C to stop and clean up.\n")

        signal.signal(signal.SIGTERM, lambda *_: sys.exit(0))
        bot.wait()  # until Ctrl+C
    except KeyboardInterrupt:
        print("\nStopping ...")
    finally:
        # Order matters: unhook Telegram first, so it stops delivering to a
        # tunnel that is about to disappear.
        try:
            telegram("deleteWebhook")
            print("Webhook deleted.")
        except SystemExit as exc:
            print(f"Could not delete the webhook: {exc}")
        processes: tuple[
            tuple[subprocess.Popen[str] | subprocess.Popen[bytes] | None, str], ...
        ] = (
            (tunnel, "tunnel"),
            (bot, "bot"),
        )
        for process, name in processes:
            if process is None or process.poll() is not None:
                continue
            process.terminate()
            try:
                process.wait(timeout=10)
            except subprocess.TimeoutExpired:
                process.kill()
            print(f"Stopped the {name}.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
